/**
 * Regenerates src/game/solana/stockList.generated.ts from Jupiter.
 *
 *   npx tsx apps/web/scripts/sync-stock-catalog.ts
 *
 * Takes every VERIFIED token Jupiter tags "stocks", keeps the 1:1-backed
 * issuers (xStocks by Backed, Backpack Securities listed via Sunrise), drops
 * thin markets (MIN_LIQUIDITY) and keeps one token per company (the more
 * liquid issuer). Pre-IPO (PreStocks), leveraged (Shift) and near-zero
 * liquidity (Ondo) products are skipped on purpose.
 *
 * The output is committed and reviewed like code: the game never looks a
 * stock up by ticker at runtime (search returns fake "NVDAx" pump tokens).
 * Descriptions, sectors and colors live in stockCatalog.ts.
 */
import fs from "node:fs";
import path from "node:path";

const MIN_LIQUIDITY = 25_000;
const OUT = path.join(__dirname, "../src/game/solana/stockList.generated.ts");

type Issuer = "xstocks" | "backpack";
interface JupToken {
  id: string; symbol: string; name: string; decimals: number; icon?: string;
  tags?: string[]; liquidity?: number; isVerified?: boolean;
}

function cleanName(name: string): string {
  return name
    .replace(/\s*-\s*Backpack Securities$/i, "")
    .replace(/\s+xStock$/i, "")
    .replace(/\s+Common Stock$/i, "")
    .replace(/,?\s+(Inc\.?|Corp\.?|Corporation|Co\.|N\.V\.|Holdings?|Group Holding|Group)$/i, "")
    .trim();
}

async function main() {
  const res = await fetch("https://lite-api.jup.ag/tokens/v2/tag?query=verified");
  if (!res.ok) throw new Error(`Jupiter tokens ${res.status}`);
  const tokens = (await res.json()) as JupToken[];

  const best = new Map<string, { token: JupToken; issuer: Issuer; ticker: string }>();
  const seen = new Set<string>();
  for (const t of tokens) {
    if (seen.has(t.id)) continue;
    seen.add(t.id);
    const tags = t.tags ?? [];
    if (!tags.includes("stocks") || !tags.includes("verified")) continue;
    const issuer: Issuer | null = tags.includes("xstocks") ? "xstocks" : tags.includes("backpack") ? "backpack" : null;
    if (!issuer || (t.liquidity ?? 0) < MIN_LIQUIDITY) continue;
    const ticker = issuer === "xstocks" ? t.symbol.replace(/x$/, "") : t.symbol;
    const cur = best.get(ticker);
    if (!cur || (t.liquidity ?? 0) > (cur.token.liquidity ?? 0)) best.set(ticker, { token: t, issuer, ticker });
  }

  const rows = [...best.values()]
    .sort((a, b) => (b.token.liquidity ?? 0) - (a.token.liquidity ?? 0))
    .map(({ token: t, issuer, ticker }) =>
      `  { ticker: ${JSON.stringify(ticker)}, tokenSymbol: ${JSON.stringify(t.symbol)}, name: ${JSON.stringify(cleanName(t.name))}, ` +
      `mint: ${JSON.stringify(t.id)}, decimals: ${t.decimals}, issuer: ${JSON.stringify(issuer)}, ` +
      `logo: ${JSON.stringify(t.icon ?? "")}, liquidity: ${Math.round(t.liquidity ?? 0)} },`);

  const file = `// GENERATED by scripts/sync-stock-catalog.ts on ${new Date().toISOString().slice(0, 10)}. Do not edit by hand.
// ${rows.length} verified 1:1 tokenized stocks with at least $${MIN_LIQUIDITY.toLocaleString("en-US")} liquidity on Jupiter.
// Liquidity (USD) is a snapshot, used only to order the catalog.

export interface GeneratedStock {
  ticker: string;
  tokenSymbol: string;
  name: string;
  mint: string;
  decimals: number;
  issuer: "xstocks" | "backpack";
  logo: string;
  liquidity: number;
}

export const GENERATED_STOCKS: readonly GeneratedStock[] = [
${rows.join("\n")}
];
`;
  fs.writeFileSync(OUT, file);
  console.log(`wrote ${rows.length} stocks to ${path.relative(process.cwd(), OUT)}`);
}

main().catch((e) => { console.error(e); process.exit(1); });
