// GENERATED by scripts/sync-stock-catalog.ts on 2026-09-18. Do not edit by hand.
// 63 verified 1:1 tokenized stocks with at least $25,000 liquidity on Jupiter.
// Liquidity (USD) is a snapshot, used only to order the catalog.

export interface GeneratedStock {
  ticker: string;
  tokenSymbol: string;
  name: string;
  mint: string;
  decimals: number;
  issuer: "xstocks" | "backpack";
  logo: string;
  liquidity: number;
}

export const GENERATED_STOCKS: readonly GeneratedStock[] = [
  { ticker: "SPY", tokenSymbol: "SPYx", name: "SP500", mint: "XsoCS1TfEyfFhfvj8EtZ528L3CaKBDBRqRapnBbDF2W", decimals: 8, issuer: "xstocks", logo: "https://xstocks-metadata.backed.fi/logos/tokens/SPYx.png", liquidity: 6648186 },
  { ticker: "MU", tokenSymbol: "MU", name: "Micron Technology", mint: "MUxEsUKSMACyw5fZf68wxf5FLnZVhtU9CwH8uNNGay1", decimals: 6, issuer: "backpack", logo: "https://backpack.exchange/api/stock-logo/MU?cacheburst=1", liquidity: 3280610 },
  { ticker: "CRCL", tokenSymbol: "CRCLx", name: "Circle", mint: "XsueG8BtpquVJX9LVLLEGuViXUungE6WmK5YZ3p3bd1", decimals: 8, issuer: "xstocks", logo: "https://xstocks-metadata.backed.fi/logos/tokens/CRCLx.png", liquidity: 2836598 },
  { ticker: "SKHY", tokenSymbol: "SKHY", name: "SK Hynix", mint: "SKHYhSjuRWHgikq8eRKbtBbpABgJSkd7ytQV14i9EQ3", decimals: 6, issuer: "backpack", logo: "https://backpack.exchange/api/stock-logo/SKHY", liquidity: 2255062 },
  { ticker: "NVDA", tokenSymbol: "NVDAx", name: "NVIDIA", mint: "Xsc9qvGR1efVDFGLrVsmkzv3qi45LTBjeUKSPmx9qEh", decimals: 8, issuer: "xstocks", logo: "https://xstocks-metadata.backed.fi/logos/tokens/NVDAx.png", liquidity: 1956891 },
  { ticker: "QQQ", tokenSymbol: "QQQx", name: "Nasdaq", mint: "Xs8S1uUs1zvS2p7iwtsG3b6fkhpvmwz4GYU3gWAmWHZ", decimals: 8, issuer: "xstocks", logo: "https://xstocks-metadata.backed.fi/logos/tokens/QQQx.png", liquidity: 1789028 },
  { ticker: "COIN", tokenSymbol: "COINx", name: "Coinbase", mint: "Xs7ZdzSHLU9ftNJsii5fCeJhoRWSC32SQGzGQtePxNu", decimals: 8, issuer: "xstocks", logo: "https://xstocks-metadata.backed.fi/logos/tokens/COINx.png", liquidity: 1294195 },
  { ticker: "TSLA", tokenSymbol: "TSLAx", name: "Tesla", mint: "XsDoVfqeBukxuZHWhdvWHBhgEHjGNst4MLodqsJHzoB", decimals: 8, issuer: "xstocks", logo: "https://xstocks-metadata.backed.fi/logos/tokens/TSLAx.png", liquidity: 1273005 },
  { ticker: "HOOD", tokenSymbol: "HOODx", name: "Robinhood", mint: "XsvNBAYkrDRNhA7wPHQfX3ZUXZyZLdnCQDfHZ56bzpg", decimals: 8, issuer: "xstocks", logo: "https://xstocks-metadata.backed.fi/logos/tokens/HOODx.png", liquidity: 1090994 },
  { ticker: "MSTR", tokenSymbol: "MSTRx", name: "MicroStrategy", mint: "XsP7xzNPvEHS1m6qfanPUGjNmdnmsLKEoNAnHjdxxyZ", decimals: 8, issuer: "xstocks", logo: "https://xstocks-metadata.backed.fi/logos/tokens/MSTRx.png", liquidity: 976009 },
  { ticker: "SPCX", tokenSymbol: "SPCXx", name: "SpaceX", mint: "Xs3oZwbHvqis4NYcf4YKWmEia2eC84wSiVrcYcTqpH8", decimals: 8, issuer: "xstocks", logo: "https://xstocks-metadata.backed.fi/logos/tokens/SPCXx.png", liquidity: 878142 },
  { ticker: "GLD", tokenSymbol: "GLDx", name: "Gold", mint: "Xsv9hRk1z5ystj9MhnA7Lq4vjSsLwzL2nxrwmwtD3re", decimals: 8, issuer: "xstocks", logo: "https://xstocks-metadata.backed.fi/logos/tokens/GLDx.png", liquidity: 612487 },
  { ticker: "AAPL", tokenSymbol: "AAPLx", name: "Apple", mint: "XsbEhLAtcf6HdfpFZ5xEMdqW8nfAvcsP5bdudRLJzJp", decimals: 8, issuer: "xstocks", logo: "https://xstocks-metadata.backed.fi/logos/tokens/AAPLx.png", liquidity: 583401 },
  { ticker: "MSFT", tokenSymbol: "MSFTx", name: "Microsoft", mint: "XspzcW1PRtgf6Wj92HCiZdjzKCyFekVD8P5Ueh3dRMX", decimals: 8, issuer: "xstocks", logo: "https://xstocks-metadata.backed.fi/logos/tokens/MSFTx.png", liquidity: 508631 },
  { ticker: "SNDK", tokenSymbol: "SNDK", name: "Sandisk", mint: "SNDKbwMUQvZhnLnxLduradgLHG5KrPuKwpnrkkGRhfH", decimals: 6, issuer: "backpack", logo: "https://backpack.exchange/api/stock-logo/SNDK", liquidity: 462048 },
  { ticker: "STRC", tokenSymbol: "STRCx", name: "Strategy PP Variable", mint: "Xs78JED6PFZxWc2wCEPspZW9kL3Se5J7L5TChKgsidH", decimals: 8, issuer: "xstocks", logo: "https://xstocks-metadata.backed.fi/logos/tokens/STRCx.png", liquidity: 458838 },
  { ticker: "MCD", tokenSymbol: "MCDx", name: "McDonald's", mint: "XsqE9cRRpzxcGKDXj1BJ7Xmg4GRhZoyY1KpmGSxAWT2", decimals: 8, issuer: "xstocks", logo: "https://xstocks-metadata.backed.fi/logos/tokens/MCDx.png", liquidity: 436932 },
  { ticker: "GOOGL", tokenSymbol: "GOOGLx", name: "Alphabet", mint: "XsCPL9dNWBMvFtTmwcCA5v3xWPSMEBCszbQdiLLq6aN", decimals: 8, issuer: "xstocks", logo: "https://xstocks-metadata.backed.fi/logos/tokens/GOOGLx.png", liquidity: 398561 },
  { ticker: "DKNG", tokenSymbol: "DKNG", name: "DraftKings", mint: "DKNGQFNGQmoBdXSRGKJ8tTu7uPDasw5JDcfMmWniNfow", decimals: 6, issuer: "backpack", logo: "https://backpack.exchange/api/stock-logo/DKNG", liquidity: 388292 },
  { ticker: "META", tokenSymbol: "METAx", name: "Meta", mint: "Xsa62P5mvPszXL1krVUnU5ar38bBSVcWAB6fmPCo5Zu", decimals: 8, issuer: "xstocks", logo: "https://xstocks-metadata.backed.fi/logos/tokens/METAx.png", liquidity: 296904 },
  { ticker: "PLTR", tokenSymbol: "PLTRx", name: "Palantir", mint: "XsoBhf2ufR8fTyNSjqfU71DYGaE6Z3SUGAidpzriAA4", decimals: 8, issuer: "xstocks", logo: "https://xstocks-metadata.backed.fi/logos/tokens/PLTRx.png", liquidity: 294271 },
  { ticker: "GRND", tokenSymbol: "GRND", name: "Grindr", mint: "GRNDYDpqwpCm6jVxpbh4xT5AM4r3p391qYsKTHqgaET2", decimals: 6, issuer: "backpack", logo: "https://backpack.exchange/api/stock-logo/GRND", liquidity: 227922 },
  { ticker: "AMZN", tokenSymbol: "AMZNx", name: "Amazon", mint: "Xs3eBt7uRfJX8QUs4suhyU8p2M6DoUDrJyWBa8LLZsg", decimals: 8, issuer: "xstocks", logo: "https://xstocks-metadata.backed.fi/logos/tokens/AMZNx.png", liquidity: 226813 },
  { ticker: "GME", tokenSymbol: "GMEx", name: "Gamestop", mint: "Xsf9mBktVB9BSU5kf4nHxPq5hCBJ2j2ui3ecFGxPRGc", decimals: 8, issuer: "xstocks", logo: "https://xstocks-metadata.backed.fi/logos/tokens/GMEx.png", liquidity: 225369 },
  { ticker: "MRNA", tokenSymbol: "MRNA", name: "Moderna", mint: "MRNAzXzhNcaEXJPibHEn8cd4vyekCDiivTyEwswLUCT", decimals: 6, issuer: "backpack", logo: "https://backpack.exchange/api/stock-logo/MRNA", liquidity: 187697 },
  { ticker: "DJT", tokenSymbol: "DJT", name: "Trump Media & Technology Group", mint: "DJTu7vi8norVzdVAffgvb39VP7wjKeTsgaMBJrzfxvoF", decimals: 6, issuer: "backpack", logo: "https://backpack.exchange/api/stock-logo/DJT", liquidity: 174236 },
  { ticker: "DRAM", tokenSymbol: "DRAM", name: "Roundhill Memory ETF", mint: "DRAMjSWR7HRfJKjRkvQWYL2bcaejaVhuxEcjf4pAY4Cw", decimals: 6, issuer: "backpack", logo: "https://backpack.exchange/api/stock-logo/DRAM", liquidity: 168523 },
  { ticker: "TTWO", tokenSymbol: "TTWO", name: "Take-Two Interactive Software", mint: "TTWofwAge91oFhZs7kpQdyrVRkmevgM88xijGvQFbKo", decimals: 6, issuer: "backpack", logo: "https://backpack.exchange/api/stock-logo/TTWO", liquidity: 161272 },
  { ticker: "KO", tokenSymbol: "KOx", name: "Coca-Cola", mint: "XsaBXg8dU5cPM6ehmVctMkVqoiRG2ZjMo1cyBJ3AykQ", decimals: 8, issuer: "xstocks", logo: "https://xstocks-metadata.backed.fi/logos/tokens/KOx.png", liquidity: 158674 },
  { ticker: "NKE", tokenSymbol: "NKE", name: "Nike", mint: "NKEda5nHhNGgjrE9nDdMvaEmkmJ96qqxzBVZEcKmjSg", decimals: 6, issuer: "backpack", logo: "https://backpack.exchange/api/stock-logo/NKE", liquidity: 157202 },
  { ticker: "AMD", tokenSymbol: "AMD", name: "Advanced Micro Devices", mint: "AMD8XwJXgQ9WV45Wyj9yFLejxzf2J6VM1PJY8bJEjeES", decimals: 6, issuer: "backpack", logo: "https://backpack.exchange/api/stock-logo/AMD", liquidity: 138868 },
  { ticker: "DFDV", tokenSymbol: "DFDVx", name: "DFDV", mint: "Xs2yquAgsHByNzx68WJC55WHjHBvG9JsMB7CWjTLyPy", decimals: 8, issuer: "xstocks", logo: "https://xstocks-metadata.backed.fi/logos/tokens/DFDVx.png", liquidity: 117283 },
  { ticker: "BRK.B", tokenSymbol: "BRK.Bx", name: "Berkshire Hathaway", mint: "Xs6B6zawENwAbWVi7w92rjazLuAr5Az59qgWKcNb45x", decimals: 8, issuer: "xstocks", logo: "https://xstocks-metadata.backed.fi/logos/tokens/BRK.Bx.png", liquidity: 105985 },
  { ticker: "RDDT", tokenSymbol: "RDDT", name: "Reddit", mint: "RDDTGbhHwVXfyCvQMXzzowKjf5qrYBZAnehoXW83ooh", decimals: 6, issuer: "backpack", logo: "https://backpack.exchange/api/stock-logo/RDDT", liquidity: 99666 },
  { ticker: "BOT", tokenSymbol: "BOT", name: "RoboStrategy", mint: "BoTx8y9ynfdxf5ZjWtCoBVkff52qKA82ysaLU8ZM6d8T", decimals: 6, issuer: "backpack", logo: "https://backpack.exchange/api/stock-logo/BOT", liquidity: 97513 },
  { ticker: "PTN", tokenSymbol: "PTN", name: "Palatin Technologies", mint: "PTNzAfFAB4LvoUQEUUGrFMyUoRLExMYjH6CcfyQfsVP", decimals: 6, issuer: "backpack", logo: "https://backpack.exchange/api/stock-logo/PTN", liquidity: 90989 },
  { ticker: "LUV", tokenSymbol: "LUV", name: "Southwest Airlines", mint: "LUV9GB51PNZNRyzzyYK3rtqFfvDvWtRiXZ34wVq2HrX", decimals: 6, issuer: "backpack", logo: "https://backpack.exchange/api/stock-logo/LUV", liquidity: 88611 },
  { ticker: "HIMS", tokenSymbol: "HIMS", name: "Hims & Hers Health", mint: "HiMSSzzwkZkrXJ4PGVJRdtfLaANeAztjjcgk5Dxe7Lwx", decimals: 6, issuer: "backpack", logo: "https://backpack.exchange/api/stock-logo/HIMS", liquidity: 83862 },
  { ticker: "AMC", tokenSymbol: "AMC", name: "AMC Entertainment", mint: "AMC1qwR9KhiyrQBRPrxnfo4JfMeMZqEBvt5tgTytNNoc", decimals: 6, issuer: "backpack", logo: "https://metadata.backpack.exchange/stock-images/backpack_securities.png", liquidity: 79063 },
  { ticker: "QUBT", tokenSymbol: "QUBT", name: "Quantum Computing", mint: "QUBTAD8C9bMU9LvmMNgKPhrmBGbHvxpu6vfWQtThxxw", decimals: 6, issuer: "backpack", logo: "https://backpack.exchange/api/stock-logo/QUBT", liquidity: 74565 },
  { ticker: "INTC", tokenSymbol: "INTC", name: "Intel", mint: "iNTCy1qTsUEZQe3DSocLz1ZXXai34Gdw8THQh5rxFaF", decimals: 6, issuer: "backpack", logo: "https://backpack.exchange/api/stock-logo/INTC", liquidity: 71226 },
  { ticker: "RUM", tokenSymbol: "RUM", name: "RUM Group", mint: "RUMsPfFZFnN1ZmGANwP7FNMJMjKH4m9RiMePrtVtLe7", decimals: 6, issuer: "backpack", logo: "https://backpack.exchange/api/stock-logo/RUM", liquidity: 70168 },
  { ticker: "BABA", tokenSymbol: "BABA", name: "Alibaba", mint: "BABANGA4JE7Kkam4nTrALAwAVgsNJUuFJnnkF7S16BZp", decimals: 6, issuer: "backpack", logo: "https://backpack.exchange/api/stock-logo/BABA", liquidity: 64570 },
  { ticker: "WULF", tokenSymbol: "WULF", name: "TeraWulf", mint: "WULFeyfrj1VJKD9HhRTcW8R4g5HefUA11HDEdBv2WxD", decimals: 6, issuer: "backpack", logo: "https://backpack.exchange/api/stock-logo/WULF", liquidity: 63625 },
  { ticker: "RBLX", tokenSymbol: "RBLX", name: "Roblox", mint: "RBLXDGRD64AtRamHMFVcjqne3Ar7NLWtFtYNtsrf1cE", decimals: 6, issuer: "backpack", logo: "https://backpack.exchange/api/stock-logo/RBLX", liquidity: 55239 },
  { ticker: "TQQQ", tokenSymbol: "TQQQx", name: "TQQQ", mint: "XsjQP3iMAaQ3kQScQKthQpx9ALRbjKAjQtHg6TFomoc", decimals: 8, issuer: "xstocks", logo: "https://xstocks-metadata.backed.fi/logos/tokens/TQQQx.png", liquidity: 53685 },
  { ticker: "AVGO", tokenSymbol: "AVGOx", name: "Broadcom", mint: "XsgSaSvNSqLTtFuyWPBhK9196Xb9Bbdyjj4fH3cPJGo", decimals: 8, issuer: "xstocks", logo: "https://xstocks-metadata.backed.fi/logos/tokens/AVGOx.png", liquidity: 50563 },
  { ticker: "BROS", tokenSymbol: "BROS", name: "Dutch Bros", mint: "BRVaZKg6J9iF2BEsdpsxJ9NyvN9PPxPZuoQUX2v8qqkk", decimals: 6, issuer: "backpack", logo: "https://backpack.exchange/api/stock-logo/BROS", liquidity: 50191 },
  { ticker: "SNAP", tokenSymbol: "SNAP", name: "Snap", mint: "SNAPcESrvnH8yUdgeMF6xm1hym9b6hW6s8YeqeHdZFz", decimals: 6, issuer: "backpack", logo: "https://backpack.exchange/api/stock-logo/SNAP", liquidity: 45345 },
  { ticker: "WEN", tokenSymbol: "WEN", name: "The Wendy's Company", mint: "WENAZ2WyPbmgvUcKfQ8hyMDfBQP9bZ65hsZ5KTFrRGZ", decimals: 6, issuer: "backpack", logo: "https://backpack.exchange/api/stock-logo/WEN", liquidity: 43129 },
  { ticker: "SPHR", tokenSymbol: "SPHR", name: "Sphere Entertainment", mint: "SPHRp8cZaSQBTp1KMNP4V1X821SXhXWt4Q2yLdyHzju", decimals: 6, issuer: "backpack", logo: "https://backpack.exchange/api/stock-logo/SPHR", liquidity: 40306 },
  { ticker: "FLWS", tokenSymbol: "FLWS", name: "1-800-FLOWERS.COM", mint: "FLWSojG1gB5VStYR3Sb4nQFRt43UBYkqih1j2CpVLqgd", decimals: 6, issuer: "backpack", logo: "https://backpack.exchange/api/stock-logo/FLWS", liquidity: 40164 },
  { ticker: "SCHH", tokenSymbol: "SCHH", name: "Schwab U.S. REIT ETF", mint: "SCHHJ3jRdSjeFEVAaLrnYdx3Brphn92Ys7z1qkiCtPX", decimals: 6, issuer: "backpack", logo: "https://backpack.exchange/api/stock-logo/SCHH", liquidity: 38634 },
  { ticker: "COST", tokenSymbol: "COST", name: "Costco Wholesale", mint: "CZEB3WNZuF2Yz1z2H81RcCk8T7fsw82KB33zqamASVsg", decimals: 6, issuer: "backpack", logo: "https://backpack.exchange/api/stock-logo/COST", liquidity: 36379 },
  { ticker: "UPS", tokenSymbol: "UPS", name: "United Parcel Service", mint: "UPSqUeMHcWbkdg784XuBUEF9DtySSnW9ur5LAVdcuB9", decimals: 6, issuer: "backpack", logo: "https://backpack.exchange/api/stock-logo/UPS", liquidity: 35779 },
  { ticker: "LULU", tokenSymbol: "LULU", name: "lululemon athletica", mint: "LULUmT9VMttkfAJE236LXJcYJ2tTP7nunrSWR5G1BdS", decimals: 6, issuer: "backpack", logo: "https://backpack.exchange/api/stock-logo/LULU", liquidity: 34754 },
  { ticker: "JNJ", tokenSymbol: "JNJ", name: "Johnson & Johnson", mint: "JNJg1znKdF712Phe7L7z52AATAvEjEytBdN2w8Lnh1Y", decimals: 6, issuer: "backpack", logo: "https://backpack.exchange/api/stock-logo/JNJ", liquidity: 33493 },
  { ticker: "BULL", tokenSymbol: "BULL", name: "Webull", mint: "BULL151gUXcFV5wXEUqu9Am2L7Qt4bTJRLRuAUjkcspC", decimals: 6, issuer: "backpack", logo: "https://backpack.exchange/api/stock-logo/BULL", liquidity: 30292 },
  { ticker: "DELL", tokenSymbol: "DELL", name: "Dell Technologies", mint: "DELL2aRKQz7DMq5DrKLtkn47ZCnbxXPZXrSGbkmd13wy", decimals: 6, issuer: "backpack", logo: "https://backpack.exchange/api/stock-logo/DELL", liquidity: 29875 },
  { ticker: "DNUT", tokenSymbol: "DNUT", name: "Krispy Kreme", mint: "DNUTsCvKbKwu2RM72cUuW3TD9YpzArzACcqYQssjPLSk", decimals: 6, issuer: "backpack", logo: "https://backpack.exchange/api/stock-logo/DNUT", liquidity: 29789 },
  { ticker: "MGM", tokenSymbol: "MGM", name: "MGM Resorts International", mint: "MGMuubtUEirmkhfEQdmGUh4pr7HuUdMWcZXFtpPbVJD", decimals: 6, issuer: "backpack", logo: "https://backpack.exchange/api/stock-logo/MGM", liquidity: 29230 },
  { ticker: "LMT", tokenSymbol: "LMT", name: "Lockheed Martin", mint: "LMT3i1BHgixFqPUgcyteJhnEz2dpy9i3cYy4pi9BoeV", decimals: 6, issuer: "backpack", logo: "https://backpack.exchange/api/stock-logo/LMT", liquidity: 27266 },
  { ticker: "HTZ", tokenSymbol: "HTZ", name: "Hertz Global Holdings", mint: "HTZsLG4zqaNvWMwXSLHH3GG5KyJpKwpBRsKVdMG6hvzP", decimals: 6, issuer: "backpack", logo: "https://backpack.exchange/api/stock-logo/HTZ", liquidity: 25974 },
];
